#!/bin/sh

mkdir "$HOME/.ssh"

printf "${SSH_KEY}" > "$HOME/.ssh/id_ed25519"

chmod 600 "$HOME/.ssh/id_ed25519"

cat > "$HOME/.ssh/config" <<dog
Host github.com
	StrictHostKeyChecking=no
dog

exec /usr/bin/sshfront -e -a /auth.sh /handler.sh
